### ISSUE TITLE
+ isn't centered for new operation button

### ISSUE THREAD

**Issue by jrozner** [theparanoids/ashirt-server#175]
The + is slightly above the center point in the circle. Setting the line height to 43px rather than 40px seems to center it but I'm not quite sure why. The width and height of the div are 40px so 40px for the line height should make sense.
<img width="154" alt="Screen Shot 2020-12-02 at 4 45 05 PM" src="https://user-images.githubusercontent.com/26415/100949650-90f05700-34bf-11eb-8ee0-c5b42dda205f.png">

**Comment by JoelAtDeluxe** [comment]
Maybe a font issue?  This is the + key... maybe this font, or most fonts, don't quite center the + sign? I could revise so that this is an image, rather than a css design + font, or change the line height, as noted

**Comment by jrozner** [comment]
Let's keep it text rather than an image and just adjust the line height.

**Comment by JoelAtDeluxe** [comment]
Keeping it as text is definitely easiest. the other option which I was looking at was a css style, which, theoretically, shouldn't be too hard. I'd like to try that before we adjust the height, as I feel like fixing the height could lead to more problems down the line, if we change fonts, or font heights.

**Comment by jrozner** [comment]
Sure, that sounds good
