### ISSUE TITLE
Make finding categories editable

### ISSUE THREAD

**Issue by jrozner** [theparanoids/ashirt-server#281]
Currently the finding categories are a fixed list of options. Let's make this editable from the admin interface and instead store them in the database.

## Requirements

1. Editing the list should be only allowed by a system administrator
2. The list of categories should be controlled system wide (not unique to a specific operation)
3. Seed data should be provided to create the current set as the default options

## Unknown questions

1. What is the behavior when a category that a finding uses is removed?

**Comment by JoelAtDeluxe** [comment]
Regarding what to do if a category is removed: two possibilities:
1. Provide a migration route where the admin can choose how to update the findings for all affected findings
2. Set the finding to "uncategorized" (this would probably be a frontend distinction. In the database, it'd probably be null.
3. Let them keep the old category. This  would be the default, as right now categories are just a separate column in the findings table, not tied to any other value.
