### ISSUE TITLE
ASHIRT Tagging Features 

### ISSUE THREAD

**Issue by melee-paranoid** [theparanoids/ashirt-server#34]
- While on tag edit page, add filter toggles to the header (filter tags by alphabetical order, by number of evidence attached, or by date tag was added) 
- While on tag edit page, clicking on tag would bring you to tag's evidence filter view

**Comment by JoelAtDeluxe** [comment]
Is the feature request to add sorting to the table by header, or add a filtering component to reduce the number of rows in the table?

**Comment by melee-paranoid** [comment]
I believe it would be to add sorting to the table by header, so the order
of the tags can be changed. It does help to see the chronological order or
the generation of tags, but sometimes I wish I could view the tags in
alphabetical order. Or sometimes I wish I knew which tag was most used, or
which tags only had 1 piece of evidence.

<http://www.verizonmedia.com>

Melissa Lee

Program Manager
Paranoids | Security Engagement

**Comment by JoelAtDeluxe** [comment]
Addressed in PR #36
