### ISSUE TITLE
In Query Builder, the combo boxes don't hide their drop downs when they become unselected.

### ISSUE THREAD

**Issue by legitimatecoder** [theparanoids/ashirt-server#340]
While viewing All Evidence on an operation with pre-existing tags and users, open the Query Builder by clicking on the pencil icon in the Filter timeline text box at the top of the screen.

Query Builder pops open.

Click into the "include tags" field.  A drop down appears with all current tags.  Do not select any tags.
Click onto the "Sort Direction" drop down, guess that it's the "Sort Direction" box because the tags list doesn't disappear and hides everything below it.
Click on the Users drop down,  same problem, all the lists are still open and overlapping.
![Screen Shot 2021-06-10 at 13 32 57](https://user-images.githubusercontent.com/50341890/121593199-81167a00-c9f0-11eb-89fb-4a02f268319e.png)

**Comment by JoelAtDeluxe** [comment]
This seems to be universal. I'll check for a solution

**Comment by JoelAtDeluxe** [comment]
the popup boxes _should_ close whenever you click outside of the area. However, the issue seems to be that popup boxes inside modals aren't experiencing this effect. This might be because both the modal and the popup are portals.
