### ISSUE TITLE
Group operations by status on main page.

### ISSUE THREAD

**Issue by legitimatecoder** [theparanoids/ashirt-server#368]
Once you have completed many operations, the main page can get very busy, with lots of completed operations filling up the page and making it harder to find a specific one still being worked on.

It would be cool to have the pending/active/complete operations in separate sections/groups for a better visual context of which ones are still being worked on.

Also, having the ability to toggle hide/collapse those groups would be useful for managing the visual clutter.

**Comment by jkennedyvz** [comment]
I've noticed my own workspace becoming a bit cluttered, great suggestion.
