### ISSUE TITLE
Multi-word tags urls on settings page go to invalid URLs in the evidence view

### ISSUE THREAD

**Issue by legitimatecoder** [theparanoids/ashirt-server#37]
If you click on a multiword tag on the settings page to view all evidence with that tag, no evidence will be displayed.

The tag is generated without a set of enclosing double quotes and thus is treated like multiple different search values.
eg you see `tag:foo bar baz`  instead of `tag:"foo bar baz"`.

**Comment by JoelAtDeluxe** [comment]
Oops. Forgot to test that scenario. Should be fixed shortly
