### ISSUE TITLE
Unable to select tags with cursor

### ISSUE THREAD

**Issue by jkennedyvz** [theparanoids/ashirt-server#39]
When editing a finding in the web ui a user can press the backspace key to remove the rightmost finding only. The cursor in the edit window does not allow selection of any preceding tags.

![image](https://user-images.githubusercontent.com/65985482/89592633-f11d0800-d801-11ea-9a01-b0cf2bea80dd.png)

**Comment by JoelAtDeluxe** [comment]
I've created a solution, but I'm not sure it's actually desirable. Try it out and let me know what you think.
