### ISSUE TITLE
Default Operation Tags

### ISSUE THREAD

**Issue by jkennedyvz** [theparanoids/ashirt-server#447]
Server administrators should be able to manage a list of default tags that are copied into new operations. This will help teams reduce tag duplication. 

In contrast to custom findings categories, we do not want to offer any default tags within the product.

**Comment by JoelAtDeluxe** [comment]
How would this work? If there are 3 default tags, when they're copied, are they true copies? I.e. in a particular project, if I need to make a modification to one, am I (an operation owner) allowed to do so, or are these only managed by admins? true copies are easier to implement, but you would effectively lose the ability to make customization while gaining the ability to make global changes.

**Comment by jkennedyvz** [comment]
They should be true copies managed by a global admin. Within an operation if a tag needed to be edited for whichever reason we would create a new tag instead.

e.g. Global admin-managed tags copied to new operation:
-Reconnaissance 
-Privilege Escalation
-Credentials

1- Hurried user begins typing "creds"
2- typeahead sees Credentials and makes it easier for the user to select with keybindings
3- If hurried user really wants to tag only "creds" they still can within the operation
4 - Hurried user should not be able to rename "Credentials" to "creds" without global admin
