### ISSUE TITLE
Add webauthn as an auth scheme

### ISSUE THREAD

**Issue by jrozner** [theparanoids/ashirt-server#457]
#304 was closed out after the auth was rebuilt to support generic OIDC2. We should evaluate adding support as webuathn as an auth scheme for non-federated authentication. Not 100% sure if it makes sense to use it simply as an alternative second factor to TOTP or as a totally separate passwordless auth scheme.

**Comment by jkennedyvz** [comment]
This should be in place by the end of Q3 along with other authentication improvements.

**Comment by jkennedyvz** [comment]
Webauthn is supported!
