### ISSUE TITLE
Display raw request/response in web

### ISSUE THREAD

**Issue by n1xbyte** [theparanoids/ashirt-server#470]
**Description:**
Currently with a HAR evidence file, all the data is displayed but there is no way easy way to reconstruct the data to see the raw request.

**Use case:**
I find a SQL injection issue and upload the evidence file. A month later I want to recreate the request. Currently, I would have to manually drop in cookies/headers/data. It would be much easier to copy/paste the data to Burp Repeater if there was an option to reconstruct the HAR and display the raw input.

**Comment by n1xbyte** [comment]
I actually found a way around this that looks really good with the current UI but doesn't quite abide by the [HAR File Format](https://w3c.github.io/web-performance/specs/HAR/Overview.html)

I have just been posting the full request content to the postData object inside the request and the content object inside response.

Not sure how extensive you want to be for future supporting HARs but it fits the bill perfect for now without have to do any HAR file reconstruction. How many outside tools generate HARs that will be used, /shrug

Request:
![image](https://user-images.githubusercontent.com/18420902/155259568-b5970701-ea88-433e-b690-2a5dbd5ba4e4.png)

Response:
![image](https://user-images.githubusercontent.com/18420902/155259613-032c47ff-1cec-4d49-a32b-ad36f059b900.png)

**Comment by JoelAtDeluxe** [comment]
I have a PR up that addresses this issue, though it likely requires more user testing. With this change, you shouldn't have to change your HARs at all.
