### ISSUE TITLE
Import/Export for default tags

### ISSUE THREAD

**Issue by jrozner** [theparanoids/ashirt-server#472]
This is dependent on #447. We should provide a way to import and export a set of default tags. Importing should not remove/replace existing tags but ideally it would function as an upsert (assuming we can get that with mysql) where it doesn't insert a duplicate name but updates the color if it exists and doesn't match the new one. Export should leave all tags in place.

Serialization format at JSON?

Use case for this is backing up/setting up a new instance as well as sharing default sets based on use case. We could provide a default set that people can import for MITRE ATT&CK and Cyber Killchain which is currently one of the ways that we're exploring using tags and saved searches. It doesn't make sense to ship these all as default and force users to manually remove them (or have them all by default) but making it easy to setup a specific workflow would be nice.

**Comment by JoelAtDeluxe** [comment]
We can do upsert in (at least) two ways with mysql:
1. start a transaction, do a look up first, and then choose the right action: i.e. fake it.
2. We should be able to do `INSERT INTO table VALUES () ON DUPLICATE KEY X UPDATE ` [documentation here](https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html)

It doesn't look like squirrel supports that kind of query building, but we can have this one entry be completely manual.

**Comment by jrozner** [comment]
That seems fine. It's not like this is going to be a common query so it doesn't need to be particularly performant. We could throw a ton of queries into a transaction and it wouldn't be an issue.
