### ISSUE TITLE
CSRF Failure

### ISSUE THREAD

**Issue by theSha1chemist** [theparanoids/ashirt-server#664]
Hi!

We love this project and want to start using it within our team, but struggling to get a prod deployment going. 

**Docker file**: Prod [ashirt-server](https://github.com/theparanoids/ashirt-server)/docker-compose-prod.yml

**OS version**: Linux 5.15.0-1011-aws 

**Description of the problem including expected versus actual behavior**:
* I expect to receive a successful response from a POST request.
* Actual behavior is a CSRF Failure. 
* Dev deployments worked okay. 
* I've tried prod deployments to multiple EC2 instances, stopping & starting, rebuilding, using different browsers on different OSs. All same error.  
 
![image](https://user-images.githubusercontent.com/3621264/187485796-2ab7823b-25c1-431c-b431-8c3863125f7a.png)
**Steps to reproduce**:

 Try this `docker-compose.yml` file:
 ```cat ashirt-server/docker-compose.yml
version: "3"
services:
  ashirt-private-service:
    build:
      context: .
      dockerfile: Dockerfile.prod.web
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      APP_CSRF_AUTH_KEY: "dummy-csrf-for-testing-prod-locally"
        #APP_IMGSTORE_BUCKET_NAME: ""
        #APP_IMGSTORE_REGION: ""
      STORE_TYPE: local
      APP_PORT: 8000
      APP_SESSION_STORE_KEY: "dummy-session-key-for-testing-prod-locally"
        #AUTH_OKTA_BACKEND_URL: "http://localhost:8080/web"
        #AUTH_OKTA_CLIENT_ID:
        #AUTH_OKTA_CLIENT_SECRET:
        #AUTH_OKTA_FAILURE_REDIRECT_URL_PREFIX: "http://localhost:8080"
        #AUTH_OKTA_ISSUER:
        #AUTH_OKTA_PROFILE_TO_SHORTNAME_FIELD: preferred_username
        #AUTH_OKTA_SUCCESS_REDIRECT_URL: "http://localhost:8080"
      AUTH_SERVICES: ashirt
      AUTH_SERVICES_ALLOW_REGISTRATION: ashirt
      DB_URI: dev-user:dev-user-password@tcp(db:3306)/dev-db


  ashirt-public-service:
    build:
      context: .
      dockerfile: Dockerfile.prod.api
    ports:
      - 8001:8000
    restart: on-failure
    environment:
      #APP_IMGSTORE_BUCKET_NAME: ""
      #APP_IMGSTORE_REGION: ""
      STORE_TYPE: local
      APP_PORT: 8000
      DB_URI: dev-user:dev-user-password@tcp(db:3306)/dev-db


  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod.frontend
    ports:
      - 8080:8080
    environment:
      NGINX_PORT: 8080
      WEB_URL: http://ashirt-private-service:8000

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
        #- ./dev_seed_data/z01_seed_data.sql:/docker-entrypoint-initdb.d/z01_seed_data.sql
        #- ./dev_seed_data/z02_gantt_operation.sql:/docker-entrypoint-initdb.d/z02_gantt_operation.sql
    environment:
      - MYSQL_DATABASE=dev-db
      - MYSQL_ROOT_PASSWORD=dev-root-password
      - MYSQL_USER=dev-user
      - MYSQL_PASSWORD=dev-user-password
  ```
 I've tried deleted and providing an empty value for `APP_CSRF_AUTH_KEY`. This resulted in a invalid json error response in the browser

**logs**:
I can provide HTTP or server side logs if requested! 

Thanks!

**Comment by jkennedyvz** [comment]
Hi @theSha1chemist ,

We'll be looking into this issue soon. FWIW the prod compose file is just a reference and we do not recommend it for production use. 

I would encourage using the [ECS-based deployment](https://github.com/theparanoids/ashirt-deployments/tree/main/ecs) since you're in AWS. That should be a more complete example of a production deployment. I'll be updating that path first with our demo ocr service.

**Comment by theSha1chemist** [comment]
The error was caused because the CSRF token was set with the SECURE flag and i wasn't using HTTPS during testing 

Thanks for advise, we will probably use ECS in the next iteration of our infra!
