### ISSUE TITLE
Export Operation to Zip File

### ISSUE THREAD

**Issue by vysecurity** [theparanoids/ashirt-server#734]
# Feature Request

## Name

Ability to export an Operation to a Zip file, including all images, texts, screen recordings, terminal recordings.

## Brief Description

Often we want to backup operational data. It would be good to be able to download all the uploaded evidence into a Zip for archival purpose. Furthermore, timestamp prepend all of the file names.

It would also be good to be able to introduce screen recordings into the evidence.

**Comment by JoelAtDeluxe** [comment]
The code is partially set up to do this, however there are a number of questions about how this would work in practice. This was an idea that was kicked around at one point, but was dropped for some reason.

Some questions that would eventually need to be answered:

* Is this export something that can be re-imported into ashirt-server?
* Who is allowed to perform an export?
* What happens to the operation on ashirt-server after someone archives it?
* what happens to the files on the file store/ s3?
* What is the utility of the export? Meaning, is this _just_ a backup, or is there some other desired utility?
* would we need/want to encrypt the zip/export format?
* is this a feature we would want to turn off for some reason?

**Comment by jkennedyvz** [comment]
> * Is this export something that can be re-imported into ashirt-server?
I believe the idea here is not to migrate an op to a new instance, but to share raw data with a 3rd party. 

> * Who is allowed to perform an export?
We probably want to limit this to operation or system admins. 

> * What happens to the operation on ashirt-server after someone archives it?
@vysecurity feel free to answer this one.  We already have the capability to delete an operation and all of its evidence, so I don't feel any automated action is necessary.

> * what happens to the files on the file store/ s3?
> * What is the utility of the export? Meaning, is this _just_ a backup, or is there some other desired utility?
see above

> * would we need/want to encrypt the zip/export format?
Considering the sensitivity of the data in ashirt we should definitely encrypt any bulk export. We should also store logs of who has created a backup somewhere in the operation settings or detailed information. 

> * is this a feature we would want to turn off for some reason?
I could see teams wanting to turn this off entirely depending on culture, but we don't have that requirement.

**Comment by jrozner** [comment]
The PR and branch that existed was #6. It doesn't look like we ever created an issue that defined the feature.

**Comment by TylerNoblett** [comment]
>  but it was a lot of code to maintain and a lot of complexity that we felt we weren't going to get significant value from or was worth the effort to support.

Now that we are interested in adding back zip file support, do you guys still feel the same regarding this statement above?
I figure I can either
1) resurrect PRs 2,3 and 6
2) use Joel's code in 6 as inspiration for adding on a zip file export feature, but start afresh
@jrozner @jkennedyvz (cc @JoelAtDeluxe)

**Comment by jrozner** [comment]
Support for this functionality was mostly requested by the community. @jkennedyvz has had the most direct contact and knows the most about what the needs are. We can discuss and make a decision on how to proceed.

**Comment by jrozner** [comment]
Chatted with @jkennedyvz and this is where we ended up:

* Export only functionality
* Export should only export the evidence (no findings, metadata, settings, or saved searches)
* Export should produce a zipped json file (including all the evidence information) and raw evidence. This probably should just be an array of objects
* Export should denormalize the the data (tags should be their values rather than the number associated with the value)
* There should be a global on/off feature set along with the other runtime flags
* It should be scoped to operation admins
* Archives should be ephemeral and just provide them to the user
