### ISSUE TITLE
`LoadAPIConfig` doesn't allow for `STORE_TYPE` configuration -- Defaults to AWS S3

### ISSUE THREAD

**Issue by cyberbutler** [theparanoids/ashirt-server#751]
The code in [/backend/config/webconfig.go](https://github.com/theparanoids/ashirt-server/blob/main/backend/config/webconfig.go) does not allow for the API service to have a specified STORE_TYPE. I believe that adding the `LoadStoreConfig` function to the `LoadAPIConfig` function would be a simple fix for this, or adding an additional attribute to the `WebConfig` struct to allow for Store Type specification. 

As observed in `/backend/config/webconfig.go`, the `LoadStoreConfig` is not currently added in the `LoadAPIConfig` return function. 
![Screenshot_2022-12-23_10-48-35](https://user-images.githubusercontent.com/46307021/209363516-547520bd-9589-4c4d-b753-3262a70a5113.png)

I am unsure if this is a bug or if there was another way I am supposed to be able to specify the STORE TYPE in production. I'm happy to submit a PR for this if you'd like.

**Comment by JoelAtDeluxe** [comment]
Hmm, yes, this does appear to be a bug. Good catch. This looks pretty small, so I might be able to get a fix up quickly.
