### ISSUE TITLE
Webauthn Login Failure

### ISSUE THREAD

**Issue by jkennedyvz** [theparanoids/ashirt-server#781]
I used ashirt-deployments to bring up the tip of main `sha-1bf765e`
When registering a new user with only webauthn the process seems to complete, but initial login fails with a 403 to the client. The username in this case was lower-alpha only. The uses appear in the database/admin settings, but the user cannot login. If I impersonate the user with a recovery link and re-add the same key the user can login. 

timestamp=2023-02-24T08:33:28.603963926Z ctx=fb404bcf-e62a-45c7-9918-06a3fd8e4ab9 msg="Error handling request" error="userHandle and User ID do not match" rootError="userHandle and User ID do not match" status=403 url=/auth/webauthn/login/finish

**Comment by jrozner** [comment]
Fixed by #800
