### ISSUE TITLE
Permalink redirects to query with invalid uuid

### ISSUE THREAD

**Issue by audibleblink** [theparanoids/ashirt-server#838]
**Golang version** (`go version`):
1.20

**OS version** (`uname -a` if on a Unix-like system):
`Linux e4449cf8fae9 4.19.0-23-cloud-amd64 #1 SMP Debian 4.19.269-1 (2022-12-20) x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:
Permalinks redirect to a search-by-uuid URL, where the actual uuid is simply the string 'uuid'

**Steps to reproduce**:

 1. Copy permalink from the evidence page
 2. Paste into browser
 3. Notice the redirection to : `https://ashirt.domain.net/operations/test-operation/evidence?q=uuid%3A:uuid`

**Comment by audibleblink** [comment]
Looks like `generatePath` from `react-router-dom` doesn't substitute query params
![image](https://github.com/theparanoids/ashirt-server/assets/4605783/a5cd4bb7-d1fd-49b3-93e8-a00e30de8737)

**Comment by JoelAtDeluxe** [comment]
hmm, looks like maybe a breaking change in react-router?

**Comment by audibleblink** [comment]
This _works_, but I have no idea what idiomatic react looks like

```patch
diff --git a/frontend/src/routes.tsx b/frontend/src/routes.tsx
index 745d4ac..7c76517 100644
--- a/frontend/src/routes.tsx
+++ b/frontend/src/routes.tsx
@@ -28,6 +28,14 @@ function Redirect(props: {
   return <Navigate to={generatePath(props.to, params)} replace />
 }

+function Permalink(props: {
+  to: string
+}) {
+  const params = useParams()
+  let query = `?q=uuid:${params.uuid}`
+  return <Navigate to={`${props.to}${query}`} replace />
+}
+
 export default () => {
   const user = React.useContext(AuthContext).user
   const isSuperAdmin = useUserIsSuperAdmin()
@@ -59,7 +67,7 @@ export default () => {
         <Route path=":slug/*" >
           <Route index element={<Redirect to={`evidence`} />} />
           <Route path="evidence" element={<AsyncEvidenceList />} />
-          <Route path="evidence/:uuid" element={<Redirect to={`../evidence?q=uuid%3A${match.params.uuid}`} />} />
+          <Route path="evidence/:uuid" element={<Permalink to={`../evidence`} />} />
           {/* ^^^ we need to do ../evidence because .. points to :slug, while . points to evidence/:uuid */}
           <Route path="findings" element={<AsyncFindingList />} />
           <Route path="findings/:uuid" element={<AsyncFindingShow />} />
```

**Comment by JoelAtDeluxe** [comment]
That's mostly what idiomatic react looks like. Thanks! I'll try this locally to see if this works for me as well.
